updating docs for vector migration by genetics changes.
EMOD-Hub/emodpy-malaria pull request #9
Opened 2024-11-23 02:42 UTC by stitova-idm

2024-11-26 04:30 UTC, Bridenbecker requested changes
Thank you for being so disciplined to update the documentation

2024-11-26 04:30 UTC, Bridenbecker commented on docs/emod/software-migration-vector.rst
> +outbound rate.
I'm still confused on the "fraction traveling" versus "rate".  Seems like it is different.  If it is not different, should we explain why it is not different?

2024-12-14 01:29 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +        python convert_csv_to_bin_vector_migration.py [input-migration-csv]
Good idea. Eventually it'll be a just part of the vector (and general) migration functionality when we overhaul the migration in emodpy. I'll add the script to emodpy-malaria for now.

2024-12-14 19:41 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +genetics of the vector.
oops. Can't mix and match those. They are definitely rates.

2024-12-14 20:12 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +per node.
left it out. It was in an old script description, I think from when you HAD to have the same DestinationsPerNode (there are some text files with a lot of 0 rates).

2024-12-14 20:13 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +        python convert_csv_to_bin_vector_migration.py [input-migration-csv]
moved all the migration scripts to emodpy_malaria/migration (renamed from vector_migration, because eventually you'll just import this for ALL the migration).

2024-12-14 20:46 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +One can have node ID's in the demographics that don't exist in the migration file.
Done

2024-12-14 21:22 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +still be important to understand the provenance and meaning of the data.
Updated the description and added a new informational parameter ("Project")

2024-12-14 21:25 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +and if included, are ignored. The omitted parameters are: MigrationType, AgesYears, InterpolationType.
removed unnecessary information.

2024-12-14 21:26 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +    IdReference, string, "(Used by |EMOD_s|.) A unique, user-selected string that indicates the method used by |EMOD_s| for generating **NodeID** values in the input files. For more information, see
changed it.

2024-12-14 21:40 UTC, stitova-idm commented on docs/emod/software-migration-vector.rst
> +outbound rate.
Added more explanation and link to code.

2024-12-16 14:56 UTC, Bridenbecker requested changes
Thank you for being on top of updating the documentation.  I'm bad at it.

I have some recommendations, but maybe we should see if Ross can look at it too before you do anything.  You might see if you can have a meeting with him so you can discuss it (and my comments) live.

2024-12-16 14:56 UTC, Bridenbecker commented on docs/emod/software-migration-vector.rst
> +Please see https://github.com/EMOD-Hub/EMOD/blob/529bd11b19b5b10d49fab445dea29ee4ebd65740/Eradication/MigrationInfoVector.cpp#L335 for further details.
Maybe replace that link with:

https://github.com/EMOD-Hub/EMOD/blob/main/Eradication/MigrationInfoVector.cpp#L335

2024-12-16 14:56 UTC, Bridenbecker commented on docs/emod/software-migration-vector.rst
> +Please see https://github.com/EMOD-Hub/EMOD/blob/529bd11b19b5b10d49fab445dea29ee4ebd65740/Eradication/MigrationInfoVector.cpp#L335 for further details.
Maybe get the equation stuff on to its own lines.  

You make a difference between the cohort and individual.  Is the result different if I use the same values?  If not, then I would not make this distinction.  For much of the vector model, we don't talk about how we use a binomial approximation for cohort versus just a uniform random number for individual.  I believe we talk about things as individuals and cohort sort of be an optimization that results in the same thing.

2024-12-16 14:56 UTC, Bridenbecker commented on docs/emod/software-migration-creation-vector.rst
> +from CSV ata using Python scripts provided by |IDM_s|. You can assign the same
This says it resolved, but I still see "ata"

2024-12-16 14:56 UTC, Bridenbecker commented on docs/emod/software-migration-creation-vector.rst
> +====================================
When I look at this file as a whole, the github version looks confusing.  The script gets lost.  Under "Create CSV Input", it reference a script immediately but I haven't really been introduced to the script.  Maybe it would be better to move the script stuff to the top and then talk about inputs and outputs.

For the input formats, I would give them each a sub-heading like:
- One rate for all types of vectors
- Different rates for male and female vectors
- Different rates depending on genetics of vector
- 
I think the sub-headings would make it easier for the user to more quickly figure out which one they want.  Hmm.  If you had the sub headings, you could put the example data under each one.  The user could see format and example side-by-side.

One thing Jen has tried to encourage us as writers is to remember that people may get this page from a search and will not have seen all the other documentation.  This means that we may need to provide information about the information not contained on the page we are working on.  I think the format of the binary file falls into that.  If you say that the script outputs the metadata file and the binary file, you can point them to the human migration file that has the format.

BTW.  The tables are a great improvement.

2024-12-16 14:56 UTC, Bridenbecker commented on docs/emod/software-migration-creation-vector.rst
> +    "[['X1','Y2']]", float, 0, 3.40282e+38, NA,"Rate at which the vector that matches this and not a more-specific allele combination will travel from the FromNodeID to ToNodeID."
We should get a Content Team opinion, but I find the example data mixed with the format definition confusing.  I would replace the last three lines with just one and put something like <allele combination> in the first column.

NOTE: I searched for "wild cards" and I didn't get it.  Make sure that indicate some where that they can use '*' when defining allele combinations.

2024-12-16 14:56 UTC, Bridenbecker commented on docs/emod/software-migration-creation-vector.rst
> +        python convert_csv_to_bin_vector_migration.py [input-migration-csv]
Now that it is part of emodpy-malaria, the command line needs to be different.  I believe you need to use the "-m" option.

2024-12-16 14:56 UTC, Bridenbecker commented on emodpy_malaria/migration/convert_csv_to_bin_vector_migration.py
> +# convert_csv_to_bin_vector_migration.py
Can you create a ticket for upgrading these files to meet our emodpy coding standard?

README - could you remove DTK from the paragraph?  Should the readme talk about these different files?

2024-12-17 00:26 UTC, stitova-idm commented on docs/emod/software-migration-vector.rst
> +Please see https://github.com/EMOD-Hub/EMOD/blob/529bd11b19b5b10d49fab445dea29ee4ebd65740/Eradication/MigrationInfoVector.cpp#L335 for further details.
Hm. The results are not different, but how we use the rates is different, but I suppose they don't need to know that. I'll clean up.

2024-12-17 02:22 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +====================================
I think I did most of this if not all.

2024-12-17 02:24 UTC, stitova-idm commented on emodpy_malaria/migration/convert_csv_to_bin_vector_migration.py
> +# convert_csv_to_bin_vector_migration.py
I plan for these files will be incorporated into migration.py in emodpy and emodpy malaria, so I'm not sure how much work we need to put into them right now?

2024-12-17 02:37 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +    "[['X1','Y2']]", float, 0, 3.40282e+38, NA,"Rate at which the vector that matches this and not a more-specific allele combination will travel from the FromNodeID to ToNodeID."
Ok. I'll talk to the doc team about this tomorrow.

2024-12-17 20:59 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +    "[['X1','Y2']]", float, 0, 3.40282e+38, NA,"Rate at which the vector that matches this and not a more-specific allele combination will travel from the FromNodeID to ToNodeID."
made updates

2024-12-17 21:54 UTC, Bridenbecker requested changes
Looks really good.  Just need to be able to call the CSV to binary from the package

2024-12-17 21:54 UTC, Bridenbecker commented on docs/emod/software-migration-creation-vector.rst
> +        python convert_csv_to_bin_vector_migration.py [input-migration-csv]
Especially if this script is going to exist in emodpy-malaria, the user should be able to use it directly from the package without needing to download it.  We don't need to update the script to meet the emodpy coding standard, but enough so they can use it from the package.

2024-12-17 21:54 UTC, Bridenbecker commented on docs/emod/software-migration-creation-vector.rst
> +CSV Input Configurations
Really love how this page has evolved.  I feel like I could quickly and easily figure out how generate the migration files I want!!

2024-12-18 01:51 UTC, Bridenbecker approved these changes
LGTM

2024-12-18 01:51 UTC, Bridenbecker commented on docs/emod/software-migration-creation-vector.rst
> +
a million characters, but that is what I was talking about.  Thank you!!

2024-12-18 18:17 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +        python convert_csv_to_bin_vector_migration.py [input-migration-csv]
Done

2024-12-18 18:18 UTC, stitova-idm commented on docs/emod/software-migration-creation-vector.rst
> +
Thankfully they can copy-paste (and I suppose we could rename it something)

2024-12-18 18:35 UTC, merged